### PR TITLE
Flush buffer when match both `start` and `end`

### LINKED ISSUE #14: Bug: Incorrect handling of lines matching both start and end regex when buffer not empty
Conditions:

- Buffer is not empty
- Line arrives which matches both multiline_start_regexp and multiline_end_regexp

Expected behavior:

1. Contents of buffer concatenated & flushed
2. New line emitted immediately

Observed behavior:

1. Contents of buffer concatenated & flushed
2. New line added to new buffer

Reproduction:

- td-agent.conf:
```
<system>
	log_level trace
</system>

<source>
	@type tail
	tag test

	path '/var/log/td-agent/test.log'

	read_from_head true

	format none
</source>


<filter test.**>
	@type record_transformer

	<record>
		label 'Pre-concat'
	</record>
</filter>
<filter test.**>
	@type stdout
</filter>


<filter test.**>
	@type concat

	key message

	multiline_start_regexp /Start/
	multiline_end_regexp   /End/

	flush_interval 10
	timeout_label @FLUSH
	use_first_timestamp true
</filter>


<filter test.**>
	@type record_transformer

	<record>
		label 'Concat-out'
	</record>
</filter>
<filter test.**>
	@type stdout
</filter>
<match **>
	@type null
</match>


<label @FLUSH>
	<filter test.**>
		@type record_transformer

		<record>
			label 'Concat-flush'
		</record>
	</filter>
	<filter test.**>
		@type stdout
	</filter>
	<match **>
		@type null
	</match>
</label>
```
- Test log generator '/etc/td-agent/test.sh':
```
#!/bin/env bash

echo "$(date) Start (Will be bumped)"
sleep 5
echo "$(date) Start End (Should return immediately; times out instead)"
```
- Execution:
```
touch '/var/log/td-agent/test.log' && chmod td-agent:td-agent '/var/log/td-agent/test.log'
service td-agent start
sh /etc/td-agent/test.sh >> '/var/log/td-agent/test.log'
```
- Output:
```
2016-08-22 17:30:31 -0400 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-08-22 17:30:31 -0400 [info]: starting fluentd-0.12.26
2016-08-22 17:30:31 -0400 [trace]: registered buffer plugin 'file'
2016-08-22 17:30:31 -0400 [trace]: registered buffer plugin 'memory'
2016-08-22 17:30:31 -0400 [trace]: registered filter plugin 'grep'
2016-08-22 17:30:31 -0400 [trace]: registered filter plugin 'record_transformer'
2016-08-22 17:30:31 -0400 [trace]: registered filter plugin 'stdout'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'debug_agent'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'dummy'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'exec'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'forward'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'gc_stat'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'http'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'monitor_agent'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'object_space'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'status'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'unix'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'syslog'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'tail'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'tcp'
2016-08-22 17:30:31 -0400 [trace]: registered input plugin 'udp'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'copy'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'exec'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'exec_filter'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'file'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'forward'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'null'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'relabel'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'roundrobin'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'stdout'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'tcp'
2016-08-22 17:30:31 -0400 [trace]: registered output plugin 'unix'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-concat' version '0.6.0'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-concat' version '0.5.0'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-forest' version '0.3.1'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-mongo' version '0.7.13'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-multi-format-parser' version '0.0.2'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-s3' version '0.6.8'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-sar' version '0.0.4'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-secure-forward' version '0.4.3'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-systemd' version '0.0.3'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-tail-multiline' version '0.1.5'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-td' version '0.10.28'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-08-22 17:30:31 -0400 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2016-08-22 17:30:31 -0400 [info]: gem 'fluentd' version '0.12.26'
2016-08-22 17:30:31 -0400 [info]: gem 'fluentd' version '0.10.61'
2016-08-22 17:30:31 -0400 [info]: adding filter in @FLUSH pattern="test.**" type="record_transformer"
2016-08-22 17:30:31 -0400 [info]: adding filter in @FLUSH pattern="test.**" type="stdout"
2016-08-22 17:30:31 -0400 [info]: adding match in @FLUSH pattern="**" type="null"
2016-08-22 17:30:31 -0400 [info]: adding filter pattern="test.**" type="record_transformer"
2016-08-22 17:30:31 -0400 [info]: adding filter pattern="test.**" type="stdout"
2016-08-22 17:30:31 -0400 [info]: adding filter pattern="test.**" type="concat"
2016-08-22 17:30:31 -0400 [trace]: registered filter plugin 'concat'
2016-08-22 17:30:31 -0400 [info]: adding filter pattern="test.**" type="record_transformer"
2016-08-22 17:30:31 -0400 [info]: adding filter pattern="test.**" type="stdout"
2016-08-22 17:30:31 -0400 [info]: adding match pattern="**" type="null"
2016-08-22 17:30:31 -0400 [info]: adding source type="tail"
2016-08-22 17:30:31 -0400 [warn]: 'pos_file PATH' parameter is not set to a 'tail' source.
2016-08-22 17:30:31 -0400 [warn]: this parameter is highly recommended to save the position to resume tailing.
2016-08-22 17:30:31 -0400 [info]: using configuration file: <ROOT>
  <system>
    log_level trace
  </system>
  <source>
    @type tail
    tag test
    path /var/log/td-agent/test.log
    read_from_head true
    format none
  </source>
  <filter test.**>
    @type record_transformer
    <record>
      label Pre-concat
    </record>
  </filter>
  <filter test.**>
    @type stdout
  </filter>
  <filter test.**>
    @type concat
    key message
    multiline_start_regexp /Start/
    multiline_end_regexp /End/
    flush_interval 10
    timeout_label @FLUSH
    use_first_timestamp true
  </filter>
  <filter test.**>
    @type record_transformer
    <record>
      label Concat-out
    </record>
  </filter>
  <filter test.**>
    @type stdout
  </filter>
  <match **>
    @type null
  </match>
  <label @FLUSH>
    <filter test.**>
      @type record_transformer
      <record>
        label Concat-flush
      </record>
    </filter>
    <filter test.**>
      @type stdout
    </filter>
    <match **>
      @type null
    </match>
  </label>
</ROOT>
2016-08-22 17:30:31 -0400 [info]: following tail of /var/log/td-agent/test.log
2016-08-22 17:30:39 -0400 test: {"message":"Mon Aug 22 17:30:39 EDT 2016 Start (Will be bumped)","label":"Pre-concat"}
2016-08-22 17:30:44 -0400 test: {"message":"Mon Aug 22 17:30:44 EDT 2016 Start End (Should return immediately; times out instead)","label":"Pre-concat"}
2016-08-22 17:30:44 -0400 test: {"message":"Mon Aug 22 17:30:39 EDT 2016 Start (Will be bumped)","label":"Concat-out"}
2016-08-22 17:30:54 -0400 test: {"message":"Mon Aug 22 17:30:44 EDT 2016 Start End (Should return immediately; times out instead)","label":"Concat-flush"}
2016-08-22 17:30:54 -0400 [info]: Timeout flush: test:default
```

Suggested fix:

The line matching logic should look something like this:
```
if buffer is empty:
	if line is startline:
		buffer.append(line)
	else:
		return line
else:
	if line is startline:
		buffer.flush()
		
	buffer.append(line)
	
	if line is endline:
		buffer.flush()
```

### PR DESCRIPTION
**Pull request by okkez**
Fix #14

### CODE REVIEW

File: lib/fluent/plugin/filter_concat.rb [hunk 1]
```diff
@@ -110,18 +110,18 @@ def process(tag, time, record)
...
         end
       when :regexp
-        if firstline?(record[@key])
+        case
+        when firstline?(record[@key])
           if @buffer[stream_identity].empty?
             @buffer[stream_identity] << [tag, time, record]
+            return flush_buffer(stream_identity) if lastline?(record[@key])
           else
             return flush_buffer(stream_identity, [tag, time, record])
```
Comment (macdjord) [inline lib/fluent/plugin/filter_concat.rb]: Bug - doesn't check if the new record is also a lastline.

Comment (macdjord) [inline lib/fluent/plugin/filter_concat.rb]: I think you may have to refactor this function. In order to handle this case (buffer not empty, new line is both start and end) properly, you need to emit _two_ logs at once: one for the previous contents of the buffer, the other for the new line.

Comment (okkez) [inline lib/fluent/plugin/filter_concat.rb]: I've already implemented so.
See https://github.com/okkez/fluent-plugin-concat/pull/16/files#diff-e73c4ffdf7080d7782bd189e8a01153eR129
